---
title: "HRU"
output: html_notebook
---

#Try to reduce the universe of possible unique parameter sets

Load libraries
```{r}
library(latex2exp)
library(gridExtra)

```


```{r}
# Select the best parameters selected from the sensitivity analysis

par_best<-bestpar$best %>%
  set_names(names(par_bound))


#HRU codes
#Mature forest        46 (MF)
#Pasture              17 (IP)
#Intermediate forest  10 (IF)
#Coffee Trianon       66 (CT)
#Coffee Orduña        58 (CO)


#Modeling ET
library(stringr)
sim_pwn_hru <- run_swat2012(project_path = path_2012,
            output = list(q_out = define_output(file = "hru",
                                  variable = "ET",
                                  unit = c(46,17,10,66,58))), # gavilanes = 15, pixquiac = 14
            parameter = par_pwn,
            start_date = "2014-01-01",
            end_date = "2017-12-31",
            years_skip = 1,
            n_thread = 4)

#Modeling WYLD
library(stringr)
sim_hru <- run_swat2012(project_path = path_2012,
            output = list(q_out = define_output(file = "hru",
                                  variable = "WYLD",
                                  unit = c(46,17,10,66,58))), # gavilanes = 15, pixquiac = 14
            parameter = par_best,
            start_date = "2014-01-01",
            end_date = "2017-12-31",
            years_skip = 1,
            n_thread = 4)


```

#FDC visualization

```{r}

HRU <- list()

# Import observed data
HRU$obs <- read.csv("C:/Veracruz/SWAT/github-rswat-ver/data/Micros.csv")

#Mature forest        46 (MF)
HRU$MF <- sim_hru$simulation$q_out_46[2:ncol(sim_hru$simulation$q_out_46)]%>%
  lapply(., sort, decreasing=T)%>%
  data.frame(.)%>%
  mutate(p = seq(0,1, length.out = nrow(.)))%>%
  melt(.,  id.vars = 'p', variable.name = 'series') #To long dataframe

#Intermediate forest  10 (IF)
HRU$IF <- sim_hru$simulation$q_out_10[2:ncol(sim_hru$simulation$q_out_10)]%>%
  lapply(., sort, decreasing=T)%>%
  data.frame(.)%>%
  mutate(p = seq(0,1, length.out = nrow(.)))%>%
  melt(.,  id.vars = 'p', variable.name = 'series') #To long dataframe


#Pasture              17 (IP)
HRU$IP <- sim_hru$simulation$q_out_17[2:ncol(sim_hru$simulation$q_out_17)]%>%
  lapply(., sort, decreasing=T)%>%
  data.frame(.)%>%
  mutate(p = seq(0,1, length.out = nrow(.)))%>%
  melt(.,  id.vars = 'p', variable.name = 'series') #To long dataframe


#Coffee Trianon       66 (CT)
HRU$CT <- sim_hru$simulation$q_out_66[2:ncol(sim_hru$simulation$q_out_66)]%>%
  lapply(., sort, decreasing=T)%>%
  data.frame(.)%>%
  mutate(p = seq(0,1, length.out = nrow(.)))%>%
  melt(.,  id.vars = 'p', variable.name = 'series') #To long dataframe


#Make the plots
plots <- list()

My_Theme = theme(plot.title = element_text(face = "bold", size= 16),axis.title = element_text(size= 14), 
                 axis.text = element_text(size = 18), legend.title = element_text(size=14), 
                 legend.text = element_text(size=14)) + theme_classic(base_size = 16)

# Plot MF
plots$a <- ggplot(HRU$MF, aes(p,value)) + geom_line(aes(colour = series)) + 
  geom_line(data=HRU$obs, aes(P_PF, Q_PF))+ scale_y_continuous(trans="log2", limits = c(0.25,32))+
  labs(title = "Mature forest")+ ylab(TeX("$Q_{mm/day}$")) + 
  xlab(TeX("Prob. of exceedence"))+ My_Theme

# Plot IF
plots$b <- ggplot(HRU$IF, aes(p,value)) + geom_line(aes(colour = series)) + 
  geom_line(data=HRU$obs, aes(P_IF, Q_IF))+
  scale_y_continuous(trans="log2",limits = c(0.25,32))+
  labs(title = "Intermediate forest")+ ylab(TeX("$Q_{mm/day}$")) + 
  xlab(TeX("Prob. of exceedence"))+ My_Theme

# Plot IP
plots$c<- ggplot(HRU$IP, aes(p,value)) + geom_line(aes(colour = series)) + 
  geom_line(data=HRU$obs, aes(P_HP, Q_HP))+
  scale_y_continuous(trans="log2", limits = c(0.25,32))+
  labs(title = "Intensive pasture")+ ylab(TeX("$Q_{mm/day}$")) + 
  xlab(TeX("Prob. of exceedence"))+ My_Theme

# Plot CT
plots$d <- ggplot(HRU$CT, aes(p,value)) + geom_line(aes(colour = series)) + 
  geom_line(data=HRU$obs, aes(P_C, Q_C))+
  scale_y_continuous(trans="log2", limits = c(0.25,32))+
  labs(title = "Shade coffee")+ ylab(TeX("$Q_{mm/day}$")) + 
  xlab(TeX("Prob. of exceedence"))+ My_Theme

ggsave(file="fdc_hru.png", plot = grid.arrange(plots$a, plots$b, plots$c, plots$d, ncol=2),
       scale = 1.5, width = 12, height = 8, dpi = 300)


ggplot() + geom_line(data=HRU$obs, aes(P_C, Q_C))+
  geom_line(data=HRU$obs, aes(P_PF, Q_PF, colour="PF"))+
  geom_line(data=HRU$obs, aes(P_IF, Q_IF, colour ="IF"))+
  geom_line(data=HRU$obs, aes(P_HP, Q_HP))+
  scale_y_continuous(trans="log2", limits = c(0.25,32))


```

#Compute statististics PBIAS Q5 and Q95

```{r}

#Compute mean quantile discharge for low flows

HRU$PBIAS95$MF <-(tapply(HRU$MF$value[HRU$MF$p > 0.945 & HRU$MF$p < 0.955], 
                      HRU$MF$series[HRU$MF$p > 0.945 & HRU$MF$p < 0.955], mean))

HRU$PBIAS9$MF <- (((HRU$PBIAS95$MF)-1.29)/1.29)*100


HRU$PBIAS95$IF <-(tapply(HRU$IF$value[HRU$IF$p > 0.945 & HRU$IF$p < 0.955], 
                      HRU$IF$series[HRU$IF$p > 0.945 & HRU$IF$p < 0.955], mean))

HRU$PBIAS95$IF <- (((HRU$PBIAS95$IF)-1.18)/1.18)*100

```



```{r}
#subset the q_sim based on q_obs using date gavilanes

HRU <- list()

lp <- 0.25
up <- 0.75


#Mature forest        46 (MF)
HRU$MF.ET05 <- apply(sim_hru$simulation$q_out_46[2:ncol(sim_hru$simulation$q_out_46)],1 , function(x) quantile(as.numeric(x),lp))

HRU$MF.ET95 <- apply(sim_pwn_hru$simulation$q_out_46[2:ncol(sim_pwn_hru$simulation$q_out_46)],1 , function(x) quantile(as.numeric(x),up))

#Pasture              17 (IP)
HRU$IP.ET05 <- apply(sim_pwn_hru$simulation$q_out_17[2:ncol(sim_pwn_hru$simulation$q_out_17)],1 , function(x) quantile(as.numeric(x),lp))
HRU$IP.ET95 <- apply(sim_pwn_hru$simulation$q_out_17[2:ncol(sim_pwn_hru$simulation$q_out_17)],1 , function(x) quantile(as.numeric(x),up))

#Intermediate forest  10 (IF)
HRU$IF.ET05 <- apply(sim_pwn_hru$simulation$q_out_10[2:ncol(sim_pwn_hru$simulation$q_out_10)],1 , function(x) quantile(as.numeric(x),lp))
HRU$IF.ET95 <- apply(sim_pwn_hru$simulation$q_out_10[2:ncol(sim_pwn_hru$simulation$q_out_10)],1 , function(x) quantile(as.numeric(x),up))

#Coffee Trianon       66 (CT)
HRU$CT.ET05 <- apply(sim_pwn_hru$simulation$q_out_66[2:ncol(sim_pwn_hru$simulation$q_out_66)],1 , function(x) quantile(as.numeric(x),lp))
HRU$CT.ET95 <- apply(sim_pwn_hru$simulation$q_out_66[2:ncol(sim_pwn_hru$simulation$q_out_66)],1 , function(x) quantile(as.numeric(x),up))

#Coffee Orduña        58 (CO)
HRU$CO.ET05 <- apply(sim_pwn_hru$simulation$q_out_58[2:ncol(sim_pwn_hru$simulation$q_out_58)],1 , function(x) quantile(as.numeric(x),lp))
HRU$CO.ET95 <- apply(sim_pwn_hru$simulation$q_out_58[2:ncol(sim_pwn_hru$simulation$q_out_58)],1 , function(x) quantile(as.numeric(x),up))

```


```{r}

#Create FDC
for(i in seq_along(HRU)){
  HRU[i] <- lapply(HRU[i],sort,decreasing=TRUE)
  print(lapply(HRU[i],mean))
  }

HRU$p <- seq(0,1, length.out=length(HRU[[1]]))

# Plot FDC
HRU <- data.frame(HRU) # works better 

ggplot() + 
  geom_ribbon(data=HRU, aes(x =p, ymin = CT.ET05, ymax = CT.ET95, fill = 'brown', alpha = 0.8)) +
  geom_ribbon(data=HRU, aes(x =p, ymin = IF.ET05, ymax = IF.ET95, fill = 'blue', alpha = 0.8)) +
  geom_ribbon(data=HRU, aes(x =p, ymin = CO.ET05, ymax = CO.ET95, fill = 'grey', alpha = 0.8)) +
  geom_ribbon(data=HRU, aes(x =p, ymin = IP.ET05, ymax = IP.ET95, fill = 'yellow', alpha = 0.8)) +
  geom_ribbon(data=HRU, aes(x =p, ymin = MF.ET05, ymax = MF.ET95, fill = 'green', alpha = 0.8)) +
  xlab('Prob of exceedance') + ylab(' WYLD mm (daily)')+
  scale_fill_identity(name = 'LC', guide = 'legend',labels = c('IF','CT','MF','CO','IP')) + 
  My_Theme


ggplot() + 
  geom_line(data=HRU, aes(p, CT.ET05), color = "brown")+
  geom_line(data=HRU, aes(p, IF.ET05), color = "blue")+
  geom_line(data=HRU, aes(p, CO.ET05), color = "grey")+
  geom_line(data=HRU, aes(p, IP.ET05), color = "yellow")+
  geom_line(data=HRU, aes(p, MF.ET05), color = "green")+
  xlab('Prob of exceedance') + ylab(' Rainfall mm (daily)')+
  scale_y_continuous(trans='log2')+
  My_Theme

```


